version: 2.1
jobs:
    trial:
      docker:
            - image: ubuntu-2004:202010-01
      parallelism: 16
      steps:
        - run:
            name: Install Dependencies
            command: |
              sleep 999999999999999


workflows:
    version: 2.1
    build:
        jobs:
        - trial
